name: Unit Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        phpunit: [10, 11, 12]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.1
            phpunit: 11
          - php: 8.1
            phpunit: 12
          - php: 8.2
            phpunit: 12

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      run: composer update --${{ matrix.dependency-version }} --with="phpunit/phpunit:^${{ matrix.phpunit }}" --no-interaction --no-progress --ansi

    - name: Unit Tests
      run: ./vendor/bin/phpunit
